name: Github Actions CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gradle Build/Test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        distribution: 'adopt'
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build;
        ./gradlew check;
        ./gradlew shadowJar -Drelease=${{startsWith(github.ref, 'refs/tags/v')}};
        ./gradlew toolDoc -Drelease=${{startsWith(github.ref, 'refs/tags/v')}};