name: Github Actions CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gradle Build/Test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-  

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        java -version;
        ./gradlew build;
        ./gradlew check;
        ./gradlew shadowJar -Drelease=${{startsWith(github.ref, 'refs/tags/v')}};
        ./gradlew toolDoc -Drelease=${{startsWith(github.ref, 'refs/tags/v')}};

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Branch name
      run: echo running on branch ${{ env.GITHUB_REF_SLUG }}

    - name: Check JAR
      run: |
        java -version
        java -jar build/libs/DISCVRSeq-${{ env.GITHUB_REF_SLUG }}.jar -h