on:
  release:
    types: [created]
name: Publish Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew build;
          ./gradlew check;
          ./gradlew shadowJar -Drelease=true;
          ./gradlew toolDoc -Drelease=true;
          mv ./build/docs ./toolDoc
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Branch name
        run: echo running on branch ${{ env.GITHUB_REF_SLUG }}
      - name: Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/libs/DISCVRSeq-${{ env.GITHUB_REF_SLUG }}.jar
      - name: GH Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./toolDoc
          enable_jekyll: true
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.6.2
        with:
          images: ghcr.io/bimberlab/discvrseq
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          version: latest
          buildkitd-flags: --debug
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.title=DISCVRSeq Toolkit
            org.opencontainers.image.description=DISCVR-seq Toolkit is a diverse collection of tools for working with sequencing data, developed and maintained by the Bimber Lab, built using the GATK4 engine.
