on:
  release:
    types: [created]
name: Publish Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew build;
          ./gradlew check;
          ./gradlew shadowJar -Drelease=true;
          ./gradlew toolDoc -Drelease=true;
          mv ./build/docs ./toolDoc
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Branch name
        run: echo running on branch ${{ env.GITHUB_REF_SLUG }}
      - name: Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/libs/DISCVRSeq-${{ env.GITHUB_REF_SLUG }}.jar
      - name: Build/Publish Docker to GHCR
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: bimberlab/discvrseq
          tag_with_ref: true
      - name: GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./toolDoc
          enable_jekyll: true